apiVersion: v1
kind: Service
metadata:
  name: hello-lucas
  labels:
    run: hello-lucas
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 20000
    protocol: TCP
    name: httpsport
  selector:
    run: hello-lucas
  externalTrafficPolicy: Cluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-lucas
spec:
  selector:
    matchLabels:
      run: hello-lucas
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        run: hello-lucas
    spec:
      containers:
      - name: hello-lucas
        image: 628006477714.dkr.ecr.us-east-2.amazonaws.com/hello_python_lucas:1.0
        # imagePullPolicy: {{imagePullPolicy}}
        resources:
          requests:
            memory: "50Mi"
          limits:
            memory: "700Mi"
            # cpu: "250m"
        ports:
        - containerPort: 5000
        # livenessProbe:
        #     httpGet:
        #             scheme: HTTP
        #             path: /
        #             port: 5000
        #     initialDelaySeconds: 600
        #     periodSeconds: 10
        # readinessProbe:
        #     httpGet:
        #             scheme: HTTP
        #             path: /
        #             port: 5000
        #     initialDelaySeconds: 180
        #     periodSeconds: 10
        env:
        - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
          value: 2019-02-20T09:41:42Z
    #   imagePullSecrets:
    #   - name: mz-regcred