version: "2.1"

services:
  tp:
    image: hello_python_lucas:1.0
    container_name: hello_python_lucas
    restart: always
    mem_limit: 500m
    environment:
        - MAX_HEAP=500m
        - TZ=Asia/Shanghai    
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    ports:
        - 9527:5000

networks:
  sonarnet:
    driver: bridge

